PSI_PROJEKAT_FINALNO/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),
    path('', include('tasha.urls'))
]

tasha/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

urlpatterns = [
    path('proizvodi/', prikazProizvoda, name='proizvodi'),
    path('zaposleni/', prikazZaposlenih, name='zaposleni'),
    path('cenovnik/', cenovnik, name='cenovnik'),
    path('jedanProizvod/', jedanProizvod, name='jedanProizvod'),
    path('add_to_cart/<int:idp>/', add_to_cart, name='add_to_cart'),
    path('update_cart/<int:idp>/<str:action>/', update_cart, name='update_cart'),
    path('finalize_order/', finalize_order, name='finalize_order'),
    path('validate_discount_code/', validate_discount_code, name='validate_discount_code'),
    path('korpa/', cart_view, name='korpa'),
    path('login/', login, name='login'),
    path('musterije/', musterije, name='musterije'),
    path('nalog/', nalog, name='nalog'),
    path('nalogOcena/', nalogOcena, name='nalogOcena'),
    path('omiljeno/', omiljeno_view, name='omiljeno'),
    path('oNama/', oNama, name='oNama'),
    path('registracija/', registracija, name='registracija'),
    path('send_html_email/<int:idrez>/', send_html_email, name='send_html_email'),
    # path('proba/', proba, name='proba'),
    path('proba1/', proba1, name='proba1'),
    path('registracijaZaposleni/', registracijaZaposleni, name='registracijaZaposleni'),
    path('izmenaLozinka/', izmenaLozinka, name='izmenaLozinka'),
    path('izmenaKorime/', izmenaKorime, name='izmenaKorime'),
    path('izmenaEmail/', izmenaEmail, name='izmenaEmail'),
    path('izmenaTelefon/', izmenaTelefon, name='izmenaTelefon'),
    path('add_to_favorites/<int:idp>/', add_to_favorites, name='add_to_favorites'),
    path('remove_from_favorites/<int:idp>/', remove_from_favorites, name='remove_from_favorites'),
    path('otkazivanjeTermina/<int:idrez>/', otkazivanjeTermina, name='otkazivanjeTermina'),
    path('proveraBrisanjaTermina/<int:idrez>/', proveraBrisanjaTermina, name='proveraBrisanjaTermina'),
    path('logout/', logout, name='logout'),
    path('zaposleniRaspored', zaposleniRaspored, name='zaposleniRaspored'),
    path('musterijaRaspored', musterijaRaspored, name='musterijaRaspored'),
    path('zaboravljena_lozinka/', zaboravljena_lozinka_view, name='zaboravljena_lozinka'),
    path('zaboravljena_lozinka/pitanja/', lozinka_pitanja_view, name='lozinka_pitanja'),
    path('zaboravljena_lozinka/promena/', lozinka_promena_view, name='lozinka_promena'),
    path('zaboravljena_lozinka/potvrda/', lozinka_promena_potvrda, name='zaboravljena_lozinka_potvrda'),
    path('delete_from_cart/<int:idp>/', delete_from_cart, name='delete_from_cart'),
    path('proizvodi/jedanProizvod/<int:idp>/', jedanProizvod, name='jedanProizvod'),
    path('zaposleni/pojedinacniZaposleni/<int:idz>/', pojedinacniZaposleni, name='pojedinacniZaposleni'),
    path('prikazMogRasporeda/', prikazMogRasporeda, name='prikazMogRasporeda'),
    path('', index, name='index')
]

tasha/forms.py
from django import forms
from .models import *

# forma za filtriranje proizvoda na osnovu kategorije - TIJANA DJUKIC
NACINI_SORTIRANJA = [
    (1, 'opadajuce'),
    (2, 'rastuce')
]
class FilterProductsKategorijaForm(forms.Form):
    kategorije = forms.MultipleChoiceField(
        choices=[],  # ovde ce zapravo biti nazivi kategorija
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    def __init__(self, *args, **kwargs):
        kategorije = kwargs.pop('categories', None)
        super(FilterProductsKategorijaForm, self).__init__(*args, **kwargs)
        if kategorije:
            self.fields['kategorije'].choices = kategorije

    sortMetoda = forms.ChoiceField(
        label= 'Sortiranje proizvoda',
        choices=NACINI_SORTIRANJA,
        widget=forms.RadioSelect(),
        required=False
    )

#forma za pretragu prizvoda/zaposlenig - TIJANA DJUKIC
class SearchForm(forms.Form):
    searchField = forms.CharField(
        label='',
        max_length=100,
        widget=forms.TextInput(
            attrs={'placeholder': 'Search . . .', 'required': True, 'class': 'form-control'}
        ),
        required=False
    )

#forma za isplatu plate zaposlenima - TIJANA DJUKIC
class DropboxZaposleni(forms.Form):
    def __init__(self, *args, **kwargs):
        zaposleni_choices = kwargs.pop('zaposleni_choices', None)
        super(DropboxZaposleni, self).__init__(*args, **kwargs)
        if zaposleni_choices:
            self.fields['zaposleni'] = forms.ChoiceField(choices=zaposleni_choices)

    zaposleni = forms.ChoiceField(
        choices=[],
        label=''
    )

#forma za zakazivanje termina - TIJANA DJUKIC
class zakazivanjeDan(forms.Form):
    tretmani = forms.ChoiceField(
        choices=[],
        label='Odaberite tretman:',
        required=True
    )

    zaposleniZak = forms.ChoiceField(
        choices=[],
        label='Odaberite zaposlenog:',
        widget=forms.RadioSelect(),
        required=True
    )

    # vreme = forms.ChoiceField(
    #     choices=[],
    #     label='',
    #     widget=forms.RadioSelect(),
    #     required=True
    # )

    datum = forms.DateField(
        label='Odaberite datum:',
        widget=forms.DateInput(attrs={'type': 'date'}),
        required=True,
    )

    def __init__(self, *args, **kwargs):
        zaposleni_choices = kwargs.pop('zaposleni_choices', None)
        tretmani_choices = kwargs.pop('tretmani_choices', None)
        zanimanje = kwargs.pop('zanimanje', None)
        # vreme_choices = kwargs.pop('vreme_choices', None)
        super(zakazivanjeDan, self).__init__(*args, **kwargs)
        if zaposleni_choices:
            self.fields['zaposleniZak'].choices = zaposleni_choices
        if tretmani_choices:
            self.fields['tretmani'].choices = tretmani_choices
        if zanimanje:
            self.fields['zaposleni'].widget.attrs['class'] = zanimanje
        # if vreme_choices:
        #     self.fields['vreme'].choices = vreme_choices

# forma za zakazivanje termina - TIJANA DJUKIC
class formaTermini(forms.Form):
    termini = forms.ChoiceField(
        choices=[],
        label='',
        widget=forms.RadioSelect(),
        required=True
    )

    def __init__(self, *args, **kwargs):
        termini_choices = kwargs.pop('termini_choices', None)
        # vreme_choices = kwargs.pop('vreme_choices', None)
        super(formaTermini, self).__init__(*args, **kwargs)
        if termini_choices:
            self.fields['termini'].choices = termini_choices

# forma potrebna za ocenjivanje zaposlenog - DJUNJA COLIC
class OcenaForm(forms.Form):
    RATING_CHOICES = [
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5'),
    ]
    ocena = forms.ChoiceField(
        choices=RATING_CHOICES,
        widget=forms.RadioSelect,
        label='Ocenite ocenom od 1 do 5'
    )

templates/cenovnik.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Cenovnik</title>
    {% load static %}
    
    <link rel="stylesheet" href="{% static 'dodatno/bootstrap.min.css' %}">
    <script src="{% static 'dodatno/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'dodatno/jquery-1.11.3.min.js' %}"></script>

    <link rel="icon" type="image/x-icon" href="{% static 'images/logo/Tasa_logo.png' %}" />

    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    
    <link rel="stylesheet" href="{% static 'css/background.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/buttons.css' %}">
    <link rel="stylesheet" href="{% static 'css/text.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/content.css' %}">
    <link rel="stylesheet" href="{% static 'css/cenovnik.css' %}">
    
    <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.css' %}">

    <script src="{% static 'js/brisanjeProzivoda.js' %}"></script>
    <script src="{% static 'js/cenovnik.js' %}"></script>
  </head>
<body>
      <div id="profile-nav">
            <div style="right: 7%; position: absolute;">
                <a href="{% url 'omiljeno' %}">
                    <i class="fa fa-heart fa-2x" aria-hidden="true" style="color:white;"></i>
                </a>
            </div>
          <div style="right: 4%; position: absolute;">
              <a href="{% url 'korpa' %}">
                  <i class="fa fa-shopping-cart fa-2x" aria-hidden="true" style="color:white;"></i>
              </a>
          </div>
          <div style="right: 1%; position: absolute;">
              <a href="{% url 'nalog' %}">
                  <i class="fa fa-user fa-2x" aria-hidden="true" style="color:white;"></i>
              </a>
          </div>
      </div>
      <nav id="menu">
        <div class="menu-item">
            <div class="menu-text">
                <a href="{% url 'index' %}">Početna</a>
            </div>
        </div>
        <div class="menu-item highlight">
            <div class="menu-text">
                <a href="{% url 'zaposleni' %}">Zaposleni</a>
            </div>
        </div>
        <div class="menu-item highlight">
            <div class="menu-text">
                <a href="{% url 'proizvodi' %}">Naši proizvodi</a>
            </div>
        </div>
        <div class="menu-item">
            <div class="menu-text">
                <a href="{% url 'oNama' %}">O nama</a>
            </div>
        </div>
        <div class="menu-item">
            <div class="menu-text">
                <a href="{% url 'cenovnik' %}">Cenovnik</a>
            </div>
        </div>
    </nav>
    <div class="naslov">
      <h1>
        NAŠE USLUGE
      </h1>
    </div>
    <div class="content2">
        <div class="row cenovnik-tabela">
            <div>
                <h1 class="podnaslov">CENOVNIK</h1>
{#                <h2 class="podnaslov2">bla bla</h2>#}
            </div>
            <br>
            <table class="table table-striped">
                <tr style="background-color: #b51b75;">
                    <th>
                        <h2>naziv</h2>
                    </th>
                    <th>
                        <h2>opis</h2>
                    </th>
                    <th>
                        <h2>cena</h2>
                    </th>
                </tr>
                {% if tretmani %}
                    {% for tretman in tretmani %}
                    	<tr>
                            <td><p><b>{{ tretman.naziv }}</b></p></td>
                            <td><p>{{ tretman.opis }}</p></td>
                            <td><p>{{ tretman.cena }}din</p></td>
                        </tr>
                    {% endfor %}
                    
                	
                {% endif %} 
            </table>
        </div>
        <br><br>
        <br><br>

    </div>
  </div>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Taša</title>
    {% load static %}

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    
    <link rel="stylesheet" href="{% static 'dodatno/bootstrap.min.css' %}">
    <script src="{% static 'dodatno/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'dodatno/jquery-1.11.3.min.js' %}"></script>
    
    <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.css' %}">
    
    <link rel="icon" type="image/x-icon" href="{% static 'images/logo/Tasa_logo.png' %}" />
    
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
    <link rel="stylesheet" href="{% static 'css/text.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/buttons.css' %}">
    <link rel="stylesheet" href="{% static 'css/shake.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">


    <!-- <script src="js/shake.js"></script> -->
    <style>
        @keyframes wave {
            0% {
                d: path("M0,32L80,53.3C160,75,320,117,480,117.3C640,117,800,75,960,53.3C1120,32,1280,32,1360,32L1440,32L1440,320L1360,320C1280,320,1120,320,960,320C800,320,640,320,480,320C320,320,160,320,80,320L0,320Z");
            }
            50% {
                d: path("M0,42L80,63.3C160,85,320,127,480,127.3C640,127,800,85,960,63.3C1120,42,1280,42,1360,42L1440,42L1440,320L1360,320C1280,320,1120,320,960,320C800,320,640,320,480,320C320,320,160,320,80,320L0,320Z");
            }
            100% {
                d: path("M0,32L80,53.3C160,75,320,117,480,117.3C640,117,800,75,960,53.3C1120,32,1280,32,1360,32L1440,32L1440,320L1360,320C1280,320,1120,320,960,320C800,320,640,320,480,320C320,320,160,320,80,320L0,320Z");
            }
        }

        .wavy-svg .top-line {
            animation: wave 5s infinite ease-in-out;
        }
    </style>
</head>
<body>
      <div id="profile-nav">
            <div style="right: 7%; position: absolute;">
                <a href="{% url 'omiljeno' %}">
                    <i class="fa fa-heart fa-2x" aria-hidden="true" style="color:white;"></i>
                </a>
            </div>
          <div style="right: 4%; position: absolute;">
              <a href="{% url 'korpa' %}">
                  <i class="fa fa-shopping-cart fa-2x" aria-hidden="true" style="color:white;"></i>
              </a>
          </div>
          <div style="right: 1%; position: absolute;">
              <a href="{% url 'nalog' %}">
                  <i class="fa fa-user fa-2x" aria-hidden="true" style="color:white;"></i>
              </a>
          </div>
      </div>
      <nav id="menu">
        <div class="menu-item">
            <div class="menu-text">
                <a href="{% url 'index' %}">Početna</a>
            </div>
        </div>
        <div class="menu-item highlight">
            <div class="menu-text">
                <a href="{% url 'zaposleni' %}">Zaposleni</a>
            </div>
        </div>
        <div class="menu-item highlight">
            <div class="menu-text">
                <a href="{% url 'proizvodi' %}">Naši proizvodi</a>
            </div>
        </div>
        <div class="menu-item">
            <div class="menu-text">
                <a href="{% url 'oNama' %}">O nama</a>
            </div>
        </div>
        <div class="menu-item">
            <div class="menu-text">
                <a href="{% url 'cenovnik' %}">Cenovnik</a>
            </div>
        </div>
    </nav>
    <div class="content">
        <div class="header">
            <h1>
                VAŠ <br>
            </h1>
            <table class="omiljeni-vreme">
                <tr>
                    <td>
                        <h1 style="color: #B51B75; top: 0;">
                            OMILJENI <br>
                        </h1>
                    </td>
                    <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
                    <td>
                        <h2 class="h2-index">
                            Pon-Ned <br>
                            9:00 - 19:00
                        </h2>
                    </td>
                </tr>
            </table>
            <h1 style="top: 0;">
                Beauty Corner <br>
            </h1>
            
            <a href="{% url 'oNama' %}"><button class="button-69 buttons-69-tirkizni" role="button">O nama</button></a>

            <img src="{% static 'images/dryer0.webp' %}" id="dryer0" class="shaker">
            <img src="{% static 'images/dryer0.webp' %}" id="dryer1" class="shaker">
            <img src="{% static 'images/dryer0.webp' %}" id="dryer2">
            <img src="{% static 'images/dryer0.webp' %}" id="dryer3" class="shaker">
            <img src="{% static 'images/dryer0.webp' %}" id="dryer4">
            <img src="{% static 'images/dryer0.webp' %}" id="dryer5">
        </div>
        <div class="wavy-div row">
            <svg class="wavy-svg" xmlns="http://www.w3.org/2000/svg" width="100%" viewBox="0 0 1440 320">
                <defs>
                    <filter id="top-shadow" x="0" y="0" width="200%" height="200%">
                        <feGaussianBlur in="SourceAlpha" stdDeviation="3" result="blur"/>
                        <feOffset in="blur" dx="0" dy="-5" result="offsetBlur"/>
                        <feFlood flood-color="black" flood-opacity="0.5"/>
                        <feComposite in2="offsetBlur" operator="in"/>
                        <feMerge>
                            <feMergeNode/>
                            <feMergeNode in="SourceGraphic"/>
                        </feMerge>
                    </filter>
                </defs>
                <path class="top-line" fill="white" fill-opacity="1" d="M0,32L80,53.3C160,75,320,117,480,117.3C640,117,800,75,960,53.3C1120,32,1280,32,1360,32L1440,32L1440,320L1360,320C1280,320,1120,320,960,320C800,320,640,320,480,320C320,320,160,320,80,320L0,320Z" filter="url(#top-shadow)"></path>
            </svg>
            <div class="wavy-content row">
                <div class="row">
                    <div class="col-6">
                        <h1 style="color: #430A5D;">
                            KAKO JE <br>
                            POČELA NAŠA <br>
                            <span style="background-color: #8ef6e4; border-radius: 15px;">
                                PRIČA?
                            </span>
                        </h1>
                    </div>
                    <div class="col-6">
                        <p class="p-content">
                            Život je kao platno, a svako lice je jedinstveno remek-delo <br> koje čeka da bude otkriveno. U srcu grada, užurbanih <br>ulica i živopisnih boja, leži ideja - kozmetički salon koji nije <br>samo mesto za negu, već oaza lepote i <br>samopouzdanja.
                        </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-4">
                        <br><br>
                        <h3 class="h3-index">
                            SA VAMA KROZ SVE BITNE <br>
                            ŽIVOTNE TRENUTKE
                        </h3>
                        <p class="p-content">
                            Istražite ponudu naših usluga.
                        </p>
                        <a href="{% url 'cenovnik' %}"><button class="button-69" role="button">Usluge</button></a>
                    </div>
                    <div class="col-8 slika-wrapper">
                        <img src="{% static 'images/animatedGirl0.png' %}" class="img-fluid mx-auto d-block" alt="Slika">
                    </div>
                    
                </div>
            </div>
        </div>
        <div class="row najbolje-ocenjen-proizvod">
            <div class="col-6">
                <img src="{% static 'images/proizvodi/slika_' %}{{ proizvod.idp }}.jpg">
            </div>
            <div class="col-6 opis">
                <h2>{{ kategorija.naziv }}</h2>
                <h1>{{ proizvod.naziv }}</h1>
                <br>
                <p class="p-content opis-proizvoda">
                    {{ proizvod.opis }}
                </p>
                <br>
                <table class="cena-i-ocena-proizvoda">
                    <tr>
                        <td class="cena">CENA <br> {{ proizvod.cena }}din</td>
                    </tr>
                </table>
                <table class="dugmici-red">
                    <tr>
                        <td>
                            <a href="{% url 'jedanProizvod' proizvod.idp %}">
								<button class="button-69 buttons-69-tirkizni" role="button">Proizvod</button>
							</a>                        
                        </td>
                        <td></td>
                        <td>
                            <button class="button-69" role="button">Kupi</button>
                        </td>
                    </tr>
                </table>
            </div>
        </div>
        <div class="row najbolje-ocenjen-zaposleni">
            <div class="col-6 opis">
                <h2>NAJBOLJE OCENJEN ZAPOSLENI</h2>
                <h1 class="ime-i-prezime">{{ zaposleni.imeprezime }}</h1>
                <br>
                <p class="p-content opis-zaposlenog">
                    Naš stručnjak za lepotu je osoba koju su naši dragi klijenti izabrali zbog izuzetne posvećenosti i veština. 
                    Njihovo bogato iskustvo u kozmetičkoj industriji obuhvata širok spektar usluga, od tretmana lica do masaža, 
                    depilacije, manikira i pedikira. Svaki korak u pružanju usluga obavlja se s ljubavlju i pažnjom, jer naš 
                    stručnjak zna da je svaki klijent poseban i zaslužuje vrhunsku negu. <br><br>

                    Ono što nasu stručnjaka čini posebnim jeste činjenica da su ga sami klijenti izabrali. Njihovo oduševljenje njegovim
                    radom neizmerno je, što potvrđuje njegovu izuzetnu sposobnost da pruži ne samo uslugu, već i iskustvo. Njegova posvećenost 
                    detaljima, ljubaznost i pažnja osiguravaju da svaki korisnik našeg salona bude oduševljen. <br><br>

                    Zahvaljujući poverenju i podršci naših klijenata, naš stručnjak je postao ključna figura u našem salonu. Njegova strast 
                    prema lepoti i stalno usavršavanje u novim tehnikama osiguravaju da naši klijenti uvek dobijaju vrhunsku uslugu koja premašuje njihova očekivanja.
                </p>
                <br>
                <table class="ocena-zaposlenog">
                    <tr>
                        <td class="ocena">OCENA <br> {{ zaposleni.ocena }}</td>
                    </tr>
                </table>
                <a href="{% url 'pojedinacniZaposleni' zaposleni.idz %}" class="read-more" id="vise1">
                    <button class="button-69" role="button" id="vise1">Više</button>
                </a>
            </div>
            <div class="col-6">
                <img src="{% static 'images/zaposleni/' %}{{ zaposleni.slika }}">
            </div>
        </div>
        <!-- <div class="footer row">
            <div class="footer-content">

            </div>
        </div> -->
    </div>
</body>
</html>

templates/izmenaTelefon.html
{% extends 'nalog.html' %}

{% block izmena %}
        <div class="izmeni-wrapper" id="izmeni-wrapper">
        <div class="izmeni">
            <a href="{% url 'nalog' %}" class="iks">
                <i class="fa fa-times fa-2x" aria-hidden="true"></i>
            </a>
            <div class="row">
                <h2 class="h2-black promena-h2">PROMENA TELEFONA</h2>
            </div>
            <form method="POST" action="{% url 'izmenaTelefon' %}">
                {% csrf_token %}
                <div class="form-row">
                    <div class="input-data">
                        <input type="text" name="telefon" required id="telefon">
                        <div class="underline"></div>
                        <label for="username"><p>Nov broj telefona ime</p></label>
                    </div>
                </div>
                <br>
                <div class="row submit-wrapper">
                    <input type="submit" value="Primenite" class="button-69 buttons-69-roze-manji" id="product-submit">
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/pojedinacniZaposleni.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Zaposleni</title>
    {% load static %}

    <link rel="stylesheet" href="{% static 'dodatno/bootstrap.min.css' %}">
    <script src="{% static 'dodatno/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'dodatno/jquery-1.11.3.min.js' %}"></script>

    <link rel="icon" type="image/x-icon" href="{% static 'images/logo/Tasa_logo.png' %}" />

    <link rel="stylesheet" href="https://www.w3schools.com/w3css/4/w3.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Montserrat">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <link rel="stylesheet" href="{% static 'css/background.css' %}">
    <link rel="stylesheet" href="{% static 'css/navbar.css' %}">
    <link rel="stylesheet" href="{% static 'css/buttons.css' %}">
    <link rel="stylesheet" href="{% static 'css/text.css' %}">
    <link rel="stylesheet" href="{% static 'css/footer.css' %}">
    <link rel="stylesheet" href="{% static 'css/content.css' %}">
    <link rel="stylesheet" href="{% static 'css/jedanProizvod.css' %}">

    <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'font-awesome-4.7.0/css/font-awesome.css' %}">

  </head>
<body>
    <div class="content overlay">
        <div class="login-form row">
            <div class="content-text">
                <h2 class="podnaslov4">
                    {{ zaposleni.imeprezime }}
                </h2>
                <br>
                <p class="opis">Zanimanje: {{ zaposleni.zanimanje }}</p>
                <p class="opis">OCENA: {{ zaposleni.ocena }}</p>
                <a href="{% url 'nalog' %}"><button class="button-69 buttons-69-tirkizni-manji" role="button">Zakaži termin</button></a>
                </div>
            <div class="div-slika">
                <a href="{% url 'zaposleni' %}" class="iks">
                    <i class="fa fa-times fa-2x" aria-hidden="true"></i>
                </a>
                <img src="{% static 'images/zaposleni/' %}{{ zaposleni.slika }}" alt="slikaProizvoda" />
            </div>
        </div>

    </div>
  </div>
</body>
</html>

templates/proba.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Proba</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/checkbox-radio.css' %}">

    <link rel="stylesheet" href="{% static 'dodatno/bootstrap.min.css' %}">
    <script src="{% static 'dodatno/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'dodatno/jquery-1.11.3.min.js' %}"></script>
</head>
<script>
    $(document).ready(function() {
        $('#id_zaposleni label').addClass('zaposleniOption');

        $('#id_tretmani').change(function() {
            let selectedOption = $(this).find(':selected');
            let selectedParsed = selectedOption.text().split(' - ');
            let kategorijaTretmana = selectedParsed[0]
            let idTretmana = $(this).val() //ovo mozda treba da se prebaci u int!!!!

            let regexKategorijaTretmana = new RegExp(kategorijaTretmana)

            $('.zaposleniOption').hide()
            $(".zaposleniOption").each(function() {
                var value = $(this).find('input').val();
                console.log(value)
                if (regexKategorijaTretmana.test(value)) {
                    $(this).show();
                }
            });
        });
    });
    </script>
<body>
    <form method="post">
        {% csrf_token %}
        {{forma.as_p}}
        <input type="submit" value="primeni" class = "button-81">
    </form>
</body>
</html>

templates/proba1.html
{% extends 'nalog.html' %}
{% block izmena %}
        <div class="izmeni-wrapper" id="izmeni-wrapper">
        <div class="izmeni">
            <a href="{% url 'nalog' %}" class="iks">
                <i class="fa fa-times fa-2x" aria-hidden="true"></i>
            </a>
            <div class="row">
                <h2 class="h2-black promena-h2">SLOBODNI TERMINI</h2>
            </div>
            {{ potvrda }}
            <form method="post">
                {% csrf_token %}
                {{ forma }}
                <input type="submit" value="rezerviši" class = "button-81">
            </form>
        </div>
    </div>
{% endblock %}